version: '2.3'
services:
  db:
    image: postgres:11.5
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    extends:
      file: common.yml
      service: app
    command: bundle exec rails server Puma -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
  gems:
