---
- name: Install packages
  become: true
  become_method: sudo
  apt:
    name: ['postgresql', 'postgresql-contrib', 'python-psycopg2', 'libpq-dev']
    state: latest
    update_cache: true
  notify: ensure postgresql is running

- name: Make sure the PostgreSQL base user is present
  postgresql_user:
    name: "{{postgresql_user}}"
    password: "{{postgresql_password}}"
    port: 5432
    state: present
    login_user: "{{postgresql_admin_user}}"
  no_log: true
  become: yes
  become_user: "{{postgresql_admin_user}}"

- name: Create PostgreSQL database
  postgresql_db:
    name: "{{postgresql_database}}"
    owner: "{{postgresql_user}}"
  become: yes
  become_user: "{{postgresql_admin_user}}"

- name: Add DATABASE_URL env var
  lineinfile:
    path: "{{item}}"
    line: "export DATABASE_URL=postgresql://{{postgresql_user}}:{{postgresql_password}}@localhost:5432/{{postgresql_database}}"
  with_items:
    - /etc/profile
    - /etc/environment
  become: yes
  become_method: sudo
