galaxy_info:
  author: pjaneiro
  description: Role to install Systemd services
  company: Whitesmith
  license: MIT
  min_ansible_version: 2.4
  # Update validated platforms when possible
  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - systemd
    - services

dependencies: []
