---
app_name: retreat
users:
  provisioner:
    name: provisioner
    comment: Application user
    groups: admin,www-data
    shell: /bin/bash
    authorized_commands:
      - "/bin/systemctl start nginx"
      - "/bin/systemctl restart nginx"
      - "/bin/systemctl stop nginx"
      - "/bin/systemctl status nginx"
      - "/bin/systemctl start puma"
      - "/bin/systemctl restart puma"
      - "/bin/systemctl stop puma"
      - "/bin/systemctl status puma"
    authorized_keys:
      - "ssh_keys/pjaneiro.pub"
services:
  puma:
    name: puma
    description: Rails Puma Webserver
    user: provisioner
    working_dir: "/var/www/{{app_name}}/current"
    executable: "/bin/bash -lc '{{rvm_root}}/gems/{{rvm_default_ruby_version}}/bin/bundle exec puma -b unix:///var/www/{{app_name}}/shared/sockets/puma.sock'"
    restart: true
    enabled: true
nginx_socket_path: "unix:///var/www/{{app_name}}/shared/sockets/puma.sock"
nginx_root: "/var/www/{{app_name}}/current/public"
letsencrypt_email: pjaneiro@whitesmith.co
postgresql_database: "{{app_name}}_production"
postgresql_user: provisioner
postgresql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30343133313739313562353735393766333061373338383332643462373336393331363736643538
          3736623934393136386565643266333065616534666634320a386664346663376563613537613163
          64666634343935616464366563333230656233646137396634633535396638376434343931306664
          6661376232303963330a386464376161643735653438346435653239323961396332613435656166
          39366333613638663438333161653936346330623734336432326439313566336333
rails_app_user: provisioner
